set positional-arguments

PNPM ?= pnpm

default:
	@just --list

install:
	{{PNPM}} install

dev:
	{{PNPM}} run dev

build:
	{{PNPM}} run build

lint:
	{{PNPM}} run lint

preview:
	{{PNPM}} run preview
